# Generated by Django 5.2.14 on 2026-05-28 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('kcal_per_100g', models.FloatField()),
                ('protein_per_100g', models.FloatField()),
                ('carbs_per_100g', models.FloatField()),
                ('fat_per_100g', models.FloatField()),
                ('fiber_per_100g', models.FloatField(default=0.0)),
                ('source', models.CharField(choices=[('openfoodfacts', 'OPEN_FOOD_FACTS'), ('manual', 'MANUAL')], default='manual', max_length=20)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'food_items',
                'indexes': [models.Index(fields=['name'], name='food_items_name_7242ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='MealEntryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_type', models.CharField(choices=[('breakfast', 'BREAKFAST'), ('lunch', 'LUNCH'), ('dinner', 'DINNER'), ('snack', 'SNACK')], max_length=20)),
                ('quantity_g', models.FloatField()),
                ('logged_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.fooditemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_entries',
                'indexes': [models.Index(fields=['user', 'logged_at'], name='meal_entrie_user_id_816550_idx')],
            },
        ),
    ]
