# Generated by Django 6.0.6 on 2026-06-12 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentrymodel',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'BREAKFAST'), ('midmorning', 'MIDMORNING'), ('lunch', 'LUNCH'), ('merienda', 'MERIENDA'), ('dinner', 'DINNER')], max_length=20),
        ),
    ]
