# Generated by Django 6.0.6 on 2026-06-12 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_mealentrymodel_meal_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedMealModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_meals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_meals',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SavedMealItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_g', models.FloatField()),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nutrition.fooditemmodel')),
                ('saved_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='nutrition.savedmealmodel')),
            ],
            options={
                'db_table': 'saved_meal_items',
            },
        ),
    ]
