# Generated by Django 6.0.6 on 2026-06-13 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroTargetHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('daily_kcal_target', models.PositiveSmallIntegerField()),
                ('protein_g_target', models.PositiveSmallIntegerField()),
                ('carbs_g_target', models.PositiveSmallIntegerField()),
                ('fat_g_target', models.PositiveSmallIntegerField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='target_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'macro_target_history',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['user', 'effective_date'], name='macro_targe_user_id_cb10e5_idx')],
                'unique_together': {('user', 'effective_date')},
            },
        ),
    ]
