# Generated by Django 6.0.6 on 2026-06-13 12:54

from django.db import migrations


def backfill(apps, schema_editor):
    """Creates an initial history row for each existing profile, with
    effective_date = the user's signup date and their current targets.
    This way all already-logged past days are associated with that target."""
    UserProfileModel = apps.get_model("infrastructure", "UserProfileModel")
    MacroTargetHistoryModel = apps.get_model("infrastructure", "MacroTargetHistoryModel")

    for profile in UserProfileModel.objects.select_related("user").all():
        effective_date = profile.user.date_joined.date()
        MacroTargetHistoryModel.objects.get_or_create(
            user=profile.user,
            effective_date=effective_date,
            defaults={
                "daily_kcal_target": profile.daily_kcal_target,
                "protein_g_target": profile.protein_g_target,
                "carbs_g_target": profile.carbs_g_target,
                "fat_g_target": profile.fat_g_target,
            },
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_macrotargethistorymodel'),
    ]

    operations = [
        migrations.RunPython(backfill, noop),
    ]
