# Generated by Django 6.0.6 on 2026-06-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0003_backfill_target_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
