# Generated by Django 5.2.14 on 2026-05-28 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('muscle_groups', models.JSONField(default=list)),
                ('equipment', models.CharField(choices=[('barbell', 'BARBELL'), ('dumbbell', 'DUMBBELL'), ('machine', 'MACHINE'), ('cable', 'CABLE'), ('bodyweight', 'BODYWEIGHT'), ('kettlebell', 'KETTLEBELL'), ('bands', 'BANDS'), ('other', 'OTHER')], max_length=20)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_exercises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercises',
            },
        ),
        migrations.CreateModel(
            name='RoutineModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'routines',
            },
        ),
        migrations.CreateModel(
            name='RoutineExerciseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField()),
                ('reps', models.PositiveSmallIntegerField()),
                ('rest_seconds', models.PositiveSmallIntegerField(default=90)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercisemodel')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_exercises', to='training.routinemodel')),
            ],
            options={
                'db_table': 'routine_exercises',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutSessionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.routinemodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workout_sessions',
            },
        ),
        migrations.CreateModel(
            name='WorkoutSetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveSmallIntegerField()),
                ('weight_kg', models.FloatField()),
                ('set_number', models.PositiveSmallIntegerField()),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('is_warmup', models.BooleanField(default=False)),
                ('is_pr', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='training.exercisemodel')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='training.workoutsessionmodel')),
            ],
            options={
                'db_table': 'workout_sets',
                'ordering': ['set_number'],
            },
        ),
        migrations.AddIndex(
            model_name='exercisemodel',
            index=models.Index(fields=['name'], name='exercises_name_26c749_idx'),
        ),
        migrations.AddIndex(
            model_name='workoutsessionmodel',
            index=models.Index(fields=['user', 'finished_at'], name='workout_ses_user_id_fdbe2b_idx'),
        ),
    ]
