# Generated by Django 5.2.14 on 2026-06-01 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsetmodel',
            name='set_type',
            field=models.CharField(default='normal', max_length=10),
        ),
    ]
