# Generated by Django 5.2.14 on 2026-06-03 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_workoutsetmodel_set_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisemodel',
            name='gif_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
