# Generated by Django 5.2.14 on 2026-06-05 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_exercisemodel_gif_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsessionmodel',
            name='calories',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ActivityLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(max_length=30)),
                ('duration_min', models.PositiveSmallIntegerField()),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField(default=0)),
                ('performed_at', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'indexes': [models.Index(fields=['user', 'performed_at'], name='activity_lo_user_id_749a5a_idx')],
            },
        ),
    ]
