# Generated by Django 6.0.6 on 2026-06-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_workoutsessionmodel_calories_activitylogmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylogmodel',
            name='route',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
