# Generated by Django 6.0.6 on 2026-06-14 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_activitylogmodel_route'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('goals', models.JSONField(default=list)),
                ('level', models.CharField(default='intermediate', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'training_plans',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingPlanDayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=12)),
                ('activity_key', models.CharField(blank=True, default='', max_length=30)),
                ('duration_min', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, default='', max_length=100)),
                ('routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.routinemodel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='training.trainingplanmodel')),
            ],
            options={
                'db_table': 'training_plan_days',
                'ordering': ['weekday'],
            },
        ),
    ]
