from django.db import models

from apps.training.domain.entities import Equipment, MuscleGroup
from apps.users.infrastructure.models import UserModel


class ExerciseModel(models.Model):
    name          = models.CharField(max_length=200, db_index=True)
    muscle_groups = models.JSONField(default=list)   # list[str] — JSONField avoids depending on Postgres
    equipment     = models.CharField(max_length=20, choices=[(e.value, e.name) for e in Equipment])
    instructions  = models.TextField(blank=True, null=True)
    gif_url       = models.URLField(blank=True, null=True)  # demonstration (object storage, not DB)
    is_custom     = models.BooleanField(default=False)
    created_by    = models.ForeignKey(
        UserModel, on_delete=models.SET_NULL,
        null=True, blank=True, related_name="custom_exercises",
    )

    class Meta:
        db_table = "exercises"
        indexes  = [models.Index(fields=["name"])]

    def __str__(self) -> str:
        return self.name


class RoutineModel(models.Model):
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="routines")
    name = models.CharField(max_length=200)

    class Meta:
        db_table = "routines"

    def __str__(self) -> str:
        return f"{self.user.email} — {self.name}"


class RoutineExerciseModel(models.Model):
    routine      = models.ForeignKey(RoutineModel, on_delete=models.CASCADE, related_name="routine_exercises")
    exercise     = models.ForeignKey(ExerciseModel, on_delete=models.PROTECT)
    sets         = models.PositiveSmallIntegerField()
    reps         = models.PositiveSmallIntegerField()
    rest_seconds = models.PositiveSmallIntegerField(default=90)
    order        = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table  = "routine_exercises"
        ordering  = ["order"]

    def __str__(self) -> str:
        return f"{self.routine.name} — {self.exercise.name}"


class WorkoutSessionModel(models.Model):
    user        = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="sessions")
    routine     = models.ForeignKey(RoutineModel, on_delete=models.SET_NULL, null=True, blank=True)
    started_at  = models.DateTimeField()
    finished_at = models.DateTimeField(null=True, blank=True, db_index=True)
    calories    = models.FloatField(default=0)   # kcal estimated on finish
    notes       = models.TextField(blank=True, null=True)

    class Meta:
        db_table = "workout_sessions"
        indexes  = [models.Index(fields=["user", "finished_at"])]

    def __str__(self) -> str:
        status = "activa" if not self.finished_at else "completada"
        return f"{self.user.email} ({status}) {self.started_at:%Y-%m-%d}"


class WorkoutSetModel(models.Model):
    session    = models.ForeignKey(WorkoutSessionModel, on_delete=models.CASCADE, related_name="sets")
    exercise   = models.ForeignKey(ExerciseModel, on_delete=models.PROTECT)
    reps       = models.PositiveSmallIntegerField()
    weight_kg  = models.FloatField()
    set_number = models.PositiveSmallIntegerField()
    rpe        = models.PositiveSmallIntegerField(null=True, blank=True)
    set_type   = models.CharField(max_length=10, default="normal")  # normal|warmup|dropset|failure
    is_warmup  = models.BooleanField(default=False)  # derived from set_type, for volume/PR queries
    is_pr      = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "workout_sets"
        ordering = ["set_number"]

    def __str__(self) -> str:
        return f"{self.exercise.name} {self.weight_kg}kg×{self.reps}"


class TrainingPlanModel(models.Model):
    """Weekly plan generated by rules (strength + cardio + mobility + rest)."""
    user       = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="training_plans")
    name       = models.CharField(max_length=200)
    goals      = models.JSONField(default=list)   # list[str]
    level      = models.CharField(max_length=20, default="intermediate")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "training_plans"
        ordering = ["-created_at"]

    def __str__(self) -> str:
        return f"{self.user.email} — {self.name}"


class TrainingPlanDayModel(models.Model):
    """A day of the plan: strength (routine), cardio, mobility or rest."""
    plan         = models.ForeignKey(TrainingPlanModel, on_delete=models.CASCADE, related_name="days")
    weekday      = models.PositiveSmallIntegerField()   # 0=Monday … 6=Sunday
    kind         = models.CharField(max_length=12)       # strength|cardio|mobility|rest
    routine      = models.ForeignKey(RoutineModel, on_delete=models.SET_NULL, null=True, blank=True)
    activity_key = models.CharField(max_length=30, blank=True, default="")
    duration_min = models.PositiveSmallIntegerField(null=True, blank=True)
    label        = models.CharField(max_length=100, blank=True, default="")

    class Meta:
        db_table = "training_plan_days"
        ordering = ["weekday"]


class ActivityLogModel(models.Model):
    """A cardio/sport activity (not strength)."""
    user         = models.ForeignKey(UserModel, on_delete=models.CASCADE, related_name="activities")
    activity_key = models.CharField(max_length=30)
    duration_min = models.PositiveSmallIntegerField()
    distance_km  = models.FloatField(null=True, blank=True)
    calories     = models.FloatField(default=0)
    # GPS route: list of [lat, lng] pairs. Empty if the activity wasn't GPS-tracked.
    route        = models.JSONField(default=list, blank=True)
    performed_at = models.DateField(db_index=True)
    created_at   = models.DateTimeField(auto_now_add=True)

    class Meta:
        db_table = "activity_logs"
        indexes  = [models.Index(fields=["user", "performed_at"])]

    def __str__(self) -> str:
        return f"{self.user.email} — {self.activity_key} ({self.performed_at})"
